name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deployment
      uses: appleboy/ssh-action@master
      env:
      	APPTOKEN: ${{ github.repository_owner }}
      with:
        host: ${{ secrets.SSH_HOST }}
        port: 22
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: APPTOKEN
        use_insecure_cipher: true
        script: |
          cd /public_html/digitalhaze/comp426
          git checkout -f
          git pull
